### ISSUE TITLE
File change notification problems (is it working? and editor reload thing)

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#206]
I opened and edited a file. (in our site)
And I resetted a commit so file change notification pop-ups.
But although I click 'Reload', editor is not reloaded.

So I tried to check it in .net site.
But it seems notification itself does not work. (maybe connection problem to notification server?)

@kyungmi Please check file change notification is working in .net site.
@happibum Please check editor reload is working in file change notification situation.

**Comment by happibum** [comment]
I have tested the current revision of webida-client attached to webida.org whose notification is working.
It seems 'reload file' does not work properly after merging PR #130.
Clearly, the client side itself has a problem and I opened a separate issue #215.

**Comment by kyungmi** [comment]
I think it is a kind of authorization issue related with recent DB refactoring.
I'll check it and notify to you what is the real problem.

**Comment by kyungmi** [comment]
There were token verification issues on webida-server and I just have resolved those issues.
But the half of the reason of this issue has stiil be in webida-client part. @happibum will handle it.

**Comment by kyungmi** [comment]
Another server-side problem has been fixed. 
Now, notification itself will work well.
