### ISSUE TITLE
Undo operation for a unexpected shortcut

### ISSUE THREAD

**Issue by hyukmin-kwon** [webida/webida-client#218]
* Undo operation for a unexpected shortcut in CodeMirror based EditorContext

**Comment by happibum** [comment]
Ctrl+U is bound to codemirror's undoSelection which is different from the usual undo.
This operation undoes not only changes but also selections. 
We decided to disable two keybindings, Ctrl+U (undoSelection) and Alt+U (redoSelection) since they are quite unusual operations.

**Comment by happibum** [comment]
There are other undocumented shortcuts. For example, 
Ctrl-Shift-Z : redo
Alt-Right : go to line end
Alt-Left : go to line start
