### ISSUE TITLE
UX improvement for 'General Web Application' configuration

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#235]
@kyungmi Please check the followings. It's from an external developer who sees our IDE first time.

1. Since path is required should be emphasized in any way
2. Selecting path should enable Debug button without need of pressing Apply button.
3. ~~Path selection dialog show all files grayed out, indicating files are not valid. Files should be displayed in normal way, instead if file is not valid OK button should be disabled.~~
4. Arguments ? and # should have at least hover hints - it is unclear what is it.
5. OK button should be changed to Close.

**Comment by kyungmi** [comment]
As for number 2, I'm going to add code to publish a topic to the run configuration plugin with validity every time the form is changed.
