### ISSUE TITLE
Can not create new account

### ISSUE THREAD

**Issue by leechwin** [webida/webida-client#237]
Can not create new account in webida.net

![account](https://cloud.githubusercontent.com/assets/510924/8717133/3d0efc2c-2bd3-11e5-8a8c-1aaee70298fb.png)

**Comment by kyungmi** [comment]
signing up is forbidden by default. But It seems to need to change the error message.

**Comment by kyungmi** [comment]
I decided to fix the error message.
Displaying wrong message was caused that server-side error message was slightly changed.
I planned to change the way of detecting error in next sprint.
