### ISSUE TITLE
Can not delete account 

### ISSUE THREAD

**Issue by leechwin** [webida/webida-client#238]
Can not delete account.

"DELETE https://auth.webida.net/webida/api/oauth/myinfo/ 500 (Internal Server Error)"

![delete](https://cloud.githubusercontent.com/assets/510924/8717145/73254b36-2bd3-11e5-8888-deae514d2ac7.png)

**Comment by kyungmi** [comment]
This is server-side "wrong-SQL" issue. I'll handle it soon.
