### ISSUE TITLE
Can not save github token

### ISSUE THREAD

**Issue by leechwin** [webida/webida-client#246]
Can not save github token

![token](https://cloud.githubusercontent.com/assets/510924/8741783/d05cc782-2c98-11e5-87eb-eed57b1ccb4a.png)

**Comment by kyungmi** [comment]
I think it is caused that your account is in unstable status because of your previous attempt removing your account. 
Your account seems to be alive now, even though your file system had been already removed.
If you need a new account, I temporarily open the singning up process. Just tell me.

**Comment by leechwin** [comment]
This issue cannot reproduce. so i close it.
