### ISSUE TITLE
Cannot login by 'Connect with Google'

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#253]
I tried to login by using "Connect with Google". However, it shows error like below:

>  #401. That’s an error.<br>
> Error: deleted_client<br>
> The OAuth client was deleted.

For more information, "Connect with Github" is working right.

**Comment by kyungmi** [comment]
I'll check

**Comment by kyungmi** [comment]
Connect with github has also issues for getting user's email address.

**Comment by kyungmi** [comment]
"Google Login" is available now. I added a app on Google Developers Console for webida oauth login by myself.
