### ISSUE TITLE
When only images are opened in editor, all menu is disabled.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#254]
Pre:
  No files are opened in editor.

1. Open more than two image files.
2. Check all menu in the top menu.

---> all menu is disabled.

After any files(not image file) are opened in editor, menu is enabled right.

**Comment by JUHYUNCHOI** [comment]
Now, some of menu is enabled. However, the enabled menu is not proper to img. files. 
For example, git menu is enabled for img. files.

**Comment by hwshim** [comment]
#834
