### ISSUE TITLE
Cannot input 'Enter' key in markdown(.md) file after opening js file

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#279]
Reproduction
1) Open IDE
2) Open js file (This opens a code editor)
3) Open md file (This opens a text editor)
4) Input 'Enter' key in the md file (This does not work. It remains nothing changed.)

'Enter' key works in an md file without opening code editor before (ie. after opening IDE without automatically opening any files)
It seems that emmet changes keyMap of codemirror when code editor is loaded and text editor is affected by the change.

This is a critical bug.

**Comment by cimfalab** [comment]
Any progress on this issue?
