### ISSUE TITLE
Ctrl+W is bound to 'close'

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#288]
In the menu, we can see the item, 'File -> Quit (Ctrl+W)'.
However, Ctrl+W seems to be bound to 'close'.
To reproduce this bug, you should use Firefox browser since Chrome will snatch Ctrl+W and try to close the browser tab.

Open a file in the editor and modify the file. Press Ctrl+W. Then, 
![image](https://cloud.githubusercontent.com/assets/10084341/8871296/2defd3d0-322f-11e5-86af-08403a6aa23f.png)
The dialog is the same when you click 'Menu -> File -> Close'.

On the other hand, when you click 'Menu -> File -> Quit (ctrl+w)',
![image](https://cloud.githubusercontent.com/assets/10084341/8871337/812268c4-322f-11e5-844e-3a290e48c00f.png)

**Comment by happibum** [comment]
Additionally, I found that
1) when the focus is at the workspace, Ctrl+W has no effect. :(
2) If the mouse focus is at the menu, Ctrl+W seems to work as 'Quit'. 

Ctrl+W is bound to 'close' when the focus is at the editor.
Therefore, we could say Ctrl+W has 3 behaviors depending on the focus.

Again note that this problem is not reproducible in Chrome browser.
Please use Firefox browser to examine this problem.

**Comment by minsung-jin** [comment]
It occurs in firefox.

**Comment by happibum** [comment]
Regarding 'close' in the editor, see line 615 of viewcontainer.js.
This call publishes the topic 'view.close' when we press ctrl+w in the editor.

**Comment by wcho** [comment]
The messages "Unsaved changes in the File to Quit" and "Save and Quit this file" are also weird.
They should be same with 'close' function becuase IDE is quitted not files. Files are closed.
