### ISSUE TITLE
Quit after modifying more than two files.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#290]
After modifying more than two files, I clicked 'File > Quit'.
Then, I found out that the msg. of dialog shows wrong file name. The file name of dialog for unsaved file is 'undefined'.

**Comment by happibum** [comment]
FYI, I attach a screenshot of this bug

![image](https://cloud.githubusercontent.com/assets/10084341/8898428/0a9c9198-345f-11e5-832c-2d963f04a236.png)
