### ISSUE TITLE
cannot duplicate a duplicated file

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#291]
1. duplicate README.md
2. duplicate README (1).md which was duplicated in step 1.

---> In step2, README (1).md is not duplicated and error toast is poped up.

**Comment by happibum** [comment]
FYI, I attach a screenshot of this bug.

![image](https://cloud.githubusercontent.com/assets/10084341/8898459/7010ec4a-345f-11e5-9a0f-23d406300f2a.png)

**Comment by happibum** [comment]
Fixed by becc58f0da7e599c10bf4068e3cf41b6d38e48a5
