### ISSUE TITLE
Number of context lines is not exact for 'git diff'

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#292]
The following screenshot is taken when I use the setting of '3 lines of context' for git diff.
As you can see, the upper context is 3 lines which is correct while the lower context is 7 lines.
This could be a non-bug. However, we at least need justification or specific condition for this behavior.

![image](https://cloud.githubusercontent.com/assets/10084341/8898336/9c5ea7d0-345d-11e5-955c-d19777763457.png)

**Comment by minsung-jin** [comment]
In general, the comparison screen is added to the margin at the top and bottom lines.
