### ISSUE TITLE
The progress bar is not disappear when git pull.

### ISSUE THREAD

**Issue by leechwin** [webida/webida-client#303]
1. Git > Pull.
2. The progress bar is not disappear.

I think side-effect by remove toast.

![image](https://cloud.githubusercontent.com/assets/510924/8910182/4d27dcdc-34c0-11e5-95e0-6058df45e1a5.png)

![image](https://cloud.githubusercontent.com/assets/510924/8910186/5261b704-34c0-11e5-82fe-d8546744a65d.png)

**Comment by happibum** [comment]
@minsung-jin Please check this issue. The error is on line 27 of notification-message.js.

**Comment by minsung-jin** [comment]
done.
