### ISSUE TITLE
Open the same file twice (in two views)

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#323]
This request is from vi server guy @darkain84.
Currently, a user can not open the same file twice. So, he can not see the same file side by side or by different position.
Please consider this request.
Server guys are saying "Terminal" and this editor feature are entry barriers to IDE, believe it or not :)

Ref 1. It's exactly like "New View into File" in Sublime Text.
Ref 2. https://www.youtube.com/watch?v=LIOWWu6rtQ0

**Comment by hyukmin-kwon** [comment]
* This issue is contained in #151 and in progress by @hwshim.

**Comment by cimfalab** [comment]
Hmm. #151 means it is possible that 'a.js' file is opened in the "Code Editor" and another "Code Editor" (same type)?
I thought #151 means 'a.js' can be opened by "Code Editor" and "Another Editor".
Please check.

**Comment by hyukmin-kwon** [comment]
Yes. #151 means that 'a.js' file is opened in the "Code Editor" and another "Code Editor" also.

**Comment by cimfalab** [comment]
Thank you :+1:

**Comment by hyukmin-kwon** [comment]
Thank you.
