### ISSUE TITLE
Quit does not work when a user access IDE directly

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#327]
Quit does not work when a user access IDE directly like:
https://webida.net/apps/ide/src/index.html?workspace=gkAn6LI4c/workspaces
(A user enters IDE url directly in the browser.)

If a user opens IDE from desktop, Quit works.
Please check it.

I can see the log in the console. Is this intended or browser limitation?
workbench-panels.js:315 Scripts may close only the windows that were opened by it.

**Comment by cimfalab** [comment]
Please comment any progress :)

**Comment by minsung-jin** [comment]
I set trick of browser opener but does not work. 
http://www.gtalbot.org/BrowserBugsSection/MSIE7Bugs/ClosingWindowsNotOpenedByJS.html

**Comment by cimfalab** [comment]
Ok. I'll take this issue as browser limitation.
Thank you.

**Comment by cimfalab** [comment]
But I think some error messages need to be shown when window.close() fails.
Please check it.
