### ISSUE TITLE
Shortcut key not working on "MultiViewerEditor's source editor tab "

### ISSUE THREAD

**Issue by gseok** [webida/webida-client#358]
* source editor tab has a 'save' item in the context menu.
* if drity mark is displayed in tab then 'save' item is activated.
* SAVE operation is working on context menu BUT if using shortcut (Ctrl + S) then not wokring.

* TEST
** webida.editor.example.multi-viewer plugin loaded
** open 'multi-page.xml' file using example.multi-viewer
** change tab 'soruce'(Code editor tab)
** edit content and dirty mark displayed
** TRY (CTRL + S).... 
** nothing to changed in editor

**Comment by hwshim** [comment]
Hyukmin kwon should solve this problem.

**Comment by gseok** [comment]
ok..
