### ISSUE TITLE
'Close All' in editor does not work in some cases

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#359]
'Close All' in editor just works as 'Close' in some cases, i.e. all opened files are not closed.
Please check the followings.
1. Open '1.html'.
2. Open '2.html'.
3. Select '1.html'.
4. Select 'File > Save Status'.
5. Refresh IDE.
6. Select 'Close All' for '1.html' in the editor tab.

In that case, only '1.html' is closed.

-----
TextEditorViewer.js:343 Uncaught TypeError: Cannot read property 'remove' of undefinedgenetic.inherits.destroyAdapter @ TextEditorViewer.js:343genetic.inherits.destroy @ TextEditorPart.js:241closeFile @ workbench-panels.js:258(anonymous function) @ workbench-panels.js:292e.(anonymous function).l

**Comment by JUHYUNCHOI** [comment]
Both 1.html and 2.html are closed now. Please check that the issue is resolved or not.

**Comment by hwshim** [comment]
@cimfalab I guess this issue has been solved.
@JUHYUNCHOI  I guess this issue has been solved.
