### ISSUE TITLE
editor content change event not fired

### ISSUE THREAD

**Issue by gseok** [webida/webida-client#400]
test env.
 - using same account
 - using same workspace and project and file

test step
1. open IDE to another env
 - window pc - chrome
 - linux pc - chrome

2. same account, same workspace and project and file open (each)
3. write file (just one side file, e.g. win-pc-chrome-ide-file)
4. select another side fie.

in this time, user expect, same file is modified in another browser (or IDE) notification
but, notification is not fired

**Comment by hwshim** [comment]
This has been solved. Thanks.
