### ISSUE TITLE
Files/directories sorting order in the workspace view

### ISSUE THREAD

**Issue by lisyoen** [webida/webida-client#401]
Files/directories sorting order in the workspace view is based on ASCII order. (A-Za-z)
for example: 
Apple.txt
Banana.txt
Cherry.txt
apple-jam.txt
banana-cookie.txt
cherry-icecream.txt

But in most cases, case-insensitive sorting is intuitive for listing files/directories.
like this: 
Apple.txt
apple-jam.txt
Banana.txt
banana-cookie.txt
Cherry.txt
cherry-icecream.txt

**Comment by wcho** [comment]
I really prefer case-sensitive order for source code files.
