### ISSUE TITLE
Workspace view flickers problem when selecting a resource

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#404]
Environment:
* Many long folders are open in workspace view across several pages
* A file is opened in editor
* A resource is selected in workspace view in the first page(ie. upper side)
Reproduce as follows
1. Select editor
2. Move mouse over workspace view and scroll down to the last page of workspace view. And the selected resource is not shown.
3. Select a resource in the last page.
Then workspace view flickers.

It seems that the workspace gets focus and shows original selected resource first while changing its style before giving focus to newly selected resource.

**Comment by minsung-jin** [comment]
After the merge and operate normally.
