### ISSUE TITLE
multiple view editor goto focus(or open) and line(column) problem

### ISSUE THREAD

**Issue by gseok** [webida/webida-client#412]
some plugins using the (or module) open editor(already opened then focus) and goto line, column.
e.g. 'Find and Files' output result click then automatically open(or focus) editor and goto line, column.

but multiple view editor not working on this operation.
need to follow functions
1. open (already opend then focus) editor
2. multiple editor has multiple tabs (ui, srouce, etc....). so auto select tab.
3. goto line and column (e.g. source tab...) or goto some ui element (e.g. ui tab...)

**Comment by cimfalab** [comment]
This can be done like the following:

```javascript
        topic.publish('editor/open', path, option, function (part) {
            var codePart = part.getContentById('<id of Code Editor>');
            var codeViewer = codePart.getViewer();
 
            // Select Code Editor tab using part.getTabContainer().
            // The returned object is dojo TabContainer.

            if (codeViewer && 'setCursor' in codeViewer) {
                codeViewer.focus();
                // TODO: ODP plans to change setCursor() like the following
                //  part.getViewer().execute('setCursor', {row: 2, col: 0});
                codeViewer.setCursor({row: 2, col: 0});
            }
        });
```

I hope it will be helpful to you.
Thank you.
