### ISSUE TITLE
multiple view editor dataSource not destroy

### ISSUE THREAD

**Issue by gseok** [webida/webida-client#413]
1. /workspace/abc/config.xml   create
2. open multiple view editor
3. code running
4. close editor
5. delete /workspace/abc/config.xml
6. create /workspace/abc/config.xml
7. open multiple view editor
8. code running

CODE
```
genetic.inherits(MyMultiViewerEditorPart, MultiViewerEditorPart, {
...
        createViewers: function () {
            var that = this;
            var dataSource = this._getDataSource();

...
```

dataSource not changed when 'step 3' and 'step 8', this mean 'step3' dataSource not clear(destroy)

**Comment by cimfalab** [comment]
@hwshim Please tell when this issue is planned to be resolved.

**Comment by gseok** [comment]
currently not resolved. so I am check the code.

CODE
```
        /**
         * @private
         */
        _onNodeDeleted: function(dataSourceId) {
            logger.info('_onNodeDeleted(' + dataSourceId + ')');
            var registry = this._getPartRegistry();
            var dsRegistry = workbench.getDataSourceRegistry();
            var dataSource = dsRegistry.getDataSourceById(dataSourceId);
            var parts = registry.getPartsByDataSource(dataSource);
            if (parts.length > 0) {
                _askClose(dataSource);
            }
        },
```
_onNodeDeleted function has bug. 'dsRegistry.unregisterDataSource(dataSource)' is not defined in _onNodeDeleted function. so I think... fix to follow code

CODE
```
        /**
         * @private
         */
        _onNodeDeleted: function(dataSourceId) {
            logger.info('_onNodeDeleted(' + dataSourceId + ')');
            var registry = this._getPartRegistry();
            var dsRegistry = workbench.getDataSourceRegistry();
            var dataSource = dsRegistry.getDataSourceById(dataSourceId);
            var parts = registry.getPartsByDataSource(dataSource);
            if (parts.length > 0) {
                _askClose(dataSource);
            }
            ///// 'parts.length === 0' logic must include!
            ///// 'parts.lenght === 0' mean some file's all part is closed, then MUST unregist data source
            else if (parts.length === 0) {
                dsRegistry.unregisterDataSource(dataSource);
            }
        },
```

**Comment by cimfalab** [comment]
@hwshim Please review this issue. I think this is so annoying.

**Comment by cimfalab** [comment]
@hwshim Please review this issue.
Above solution commented by @gseok works only for the one file opened in the editor.
It's good but it does not resolve the issue when a project folder is deleted.
Please fix this issue in the editor framework.

**Comment by gseok** [comment]
I expect to If modify the code of '_onNodeDeleted' function then 'file' and 'dir' to delete problems are resolved. But it's not resolved. So I think. 'onDirDeleted' need to modify the code also appears.

**Comment by gseok** [comment]
```
           //on deleted
            this.subscribed.push(topic.subscribe('workspace.nodes.deleting', this._onNodesDeleted.bind(this)));
            this.subscribed.push(topic.subscribe('fs.cache.node.deleted', this._checkCase.bind(this)));
```

We found follow bug. so That code (using 'workspace.nodes.deleting', 'fs.cache.node.deleted')
These fs events can be fired even though a file is not really added(or delete) to workspace.
For example, if you expand a folder in some depth that have not visited yet, 'fs.cache.node.added' will be fired.
So you consider to change event name.
'sys.fs.file.written' and 'sys.fs.file.deleted' for detecting "real" file add or remove.

**Comment by hwshim** [comment]
@cimfalab : I added code for cleaning up the DataSource of MultiContentEditorPart.
@gseok : I solved this issue. Please refer to following commits.
1242363f4aa048115c932ca22b1ef11eab20ad9c
431f3d8637bc29b1d136a9ff02b8891aada93fde
30f950d96cd1138d2bf5d69271629c7c1a55eea6
