### ISSUE TITLE
Untracked files are not shown correctly in workspace when the files are get untracked by mixed reset in other IDE.

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#434]
![image](https://cloud.githubusercontent.com/assets/10084341/9810940/00f3e3ca-58af-11e5-8bfb-d91786b7bf5d.png)

j.js and k.js are untracked after mixed reset done in other IDE. 
However, this IDE still shows that j.js and k.js are in tracked status.

**Comment by minsung-jin** [comment]
done.
