### ISSUE TITLE
Existing branches are not shown in 'Create branch' dialog

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#436]
![image](https://cloud.githubusercontent.com/assets/10084341/9810989/650679c2-58af-11e5-933b-908ca44104b8.png)

Steps are:
1. create new branch named 'test'
2. Before 'Local branches' and 'Remote branches' get refreshed, click 'Create' button'.
Then, the dropdown list of 'Branch' does not show any existing branches.

**Comment by minsung-jin** [comment]
done.
