### ISSUE TITLE
Editors does not know directory name changes in workspace

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#440]
![image](https://cloud.githubusercontent.com/assets/10084341/9811356/9e711fbc-58b1-11e5-9f57-b6ca98d0dbef.png)

Steps are:
1. create directory named 'aa'
2. create file named 'bb.js' in 'aa' directory.
3. open bb.js in editor.
4. rename 'aa' to 'cc'
5. turn on 'sync with editor'
We can see toast error message saying 'aa/bb.js' does not exist. 
However, when we modify bb.js and save it, we can find the changes in 'cc/bb.js'

**Comment by hwshim** [comment]
#740
