### ISSUE TITLE
Sync with editor does not work when the file is moved.

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#442]
![image](https://cloud.githubusercontent.com/assets/10084341/9811592/3ae7ce26-58b3-11e5-9546-f023b2b21669.png)

Steps are:
1. Open file 'cc/bb.js'
2. Move 'bb.js' to 'dd'
3. Turn on 'sync with editor' (or toggle twice)
The the toast error message is shown.
Interestingly, if we modify bb.js and save it, we can find the change in 'dd/bb.js'.

**Comment by hwshim** [comment]
Solved
