### ISSUE TITLE
A text file uploaded from windows is in modified status just after opening it.

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#443]

**Comment by happibum** [comment]
As of late July, codemirror has a new option called 'lineSeparator',
which seems relevant to this problem.
Though the option may not solve our problem completely, it could still be useful.

**Comment by hwshim** [comment]
@happibum 
Please update codemirror folk as a latest version.
Then #707  will work.
Thanks.

**Comment by happibum** [comment]
Resolved by both #707 and #738
