### ISSUE TITLE
Updated file isn't uploaded in other opened IDE.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#483]
Pre-Condition : More than two ide are opened with the same workspace.

1. Edit and save am existed file in workspace 'Test'.
2. Other IDE which was opened with the same workspace 'Test' must pop up a dialog for upload alarm.
However, there is not only dialog alarm but also updated file.

**Comment by cimfalab** [comment]
Is this related with #400 ?
