### ISSUE TITLE
Notification problem (The session id of a notification is unknown)

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#490]
Notification may not be working.
If I create a project by Project Wizard, the following error is shown in console.
Please check it.

The session id of a notification is unknown
isIgnoredNotification @ FSCache-0.1.js:1268
(anonymous function) @ FSCache-0.1.js:1286
e.(anonymous function).l @ dojo.js:237
h.emit @ dojo.js:214
h.emit @ dojo.js:215
f.emit @ dojo.js:178
publish @ dojo.js:191
webida.auth.getMyInfo.callbacks.topicsysnotify @ app.js:416
msg_topicSysNtf @ msg.js:211

**Comment by kyungmi** [comment]
@cimfalab It seems to be resolved with #104 as I tested. Please check it again.

**Comment by cimfalab** [comment]
The error message is now shown any more.
Do you really mean #104 ?

**Comment by kyungmi** [comment]
Oh... sorry. That is PR#104(https://github.com/webida/webida-server/pull/104).

**Comment by cimfalab** [comment]
Thank you^^
