### ISSUE TITLE
Cannot type right after opening a file.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#523]
1. Open 1.html.
2. Click editor of 1.html.
Problem: Green cursor exists in the editor. Then I cannot type anything at all for a while.

![idebug](https://cloud.githubusercontent.com/assets/7767406/10185932/d3b01388-6787-11e5-82b4-7aa2a439523c.png)

**Comment by hwshim** [comment]
@JUHYUNCHOI : This is because of the focus. I'll solve this in 1.5.0. Thanks.

**Comment by hwshim** [comment]
@JUHYUNCHOI : This issue is related to https://github.com/webida/webida-client/issues/513
