### ISSUE TITLE
What is a profile for?

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#556]
What is a profile for?

I changed a profile, but nothing happened. 
Furthermore, I have no idea what to do with 'Location' and 'Gravatar'.

I'd like to have any tips how or what to do with a profile.

**Comment by lisyoen** [comment]
I agree that the tip is needed.
And 'Gravatar' is a service that you can register your avatar.
You can touch that from 'http://gravatar.com'
(Actually, I didn't know that before this work - renewal dashboard)
