### ISSUE TITLE
Bugs in 'Forgot your password?'

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#558]
1. Select 'Forgot your password?'.
2. Make window smaller.
3. Input 'aa' in the input box and enter.
4. Input a correct email address in the input box and enter.
5. Input 'aa' in the input box and enter.
6. Input 'aabb' in the input box and enter.
7. Select 'Back'.
8. Select 'Forgot your password?'.

Instruction msg : 
We've sent an email with instructions on how to reset your password.
If you don't receive instructions within a few minutes, check your email's spam and junk filters.

**Bug1**. UI is broken. Refer to the img. below.
**Bug2**. Even though 'aa' is wrong format of email address, the instruction msg is displayed. (Step3)
**Bug3**. 'aabb' is considered as wrong email address (not like 'aa'). Therefore, error msg is displayed.
                The problem is that the instruction msg still exist. (Step 6)
**Bug4**.  Error msg. and instruction msg exist even though no actions have done. (Step8)

IMG.
![login](https://cloud.githubusercontent.com/assets/7767406/10362962/80f33452-6dec-11e5-8a68-333fd9d02b63.png)

**Comment by hwshim** [comment]
@JUHYUNCHOI 

moved to https://github.com/webida/webida-dashboard/issues/54
