### ISSUE TITLE
Closable and dynamically-added view is not closed

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#560]
Closable and dynamically-added view like 'Project > Export' is not closed.
After opening the view by selecting 'Project > Export' main menu,
I can not close the view by clicking 'x' icon in the view tab.

Error is the following:
/common/src/webida/widgets/views/viewcontainer.js:610
Uncaught TypeError: Cannot read property 'getPart' of undefined
viewContainer._contentPaneClose @ /common/src/webida/widgets/views/viewcontainer.js:610

Current changes for EditorPart? ViewPart? affect to this.
Please check.

**Comment by hwshim** [comment]
@cimfalab 
Please see https://github.com/webida/webida-client/pull/595
