### ISSUE TITLE
Failed to drag and drop a directory with spaces in its name

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#566]
When drag and drop a directory with spaces in its name, it calls fs rename api with html entity escaped name(such as "/workspace/project&nbsp;1"). This is related with #374. It seems that handling spaces in the name is not complete.

I think current implementation that keeps esacaped string in node.name is not good. Keep the node.name with original name without escaping and only escape it when showing. Escaping is for browser rendering and it's not a part of model (the node objects).

**Comment by minsung-jin** [comment]
done.
