### ISSUE TITLE
Please remove log for entire file content in the editor framework

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#571]
@hwshim 
I see a bunch of logs after upgrading editor framework.
Especially, entire file contents are shown in the info logs.
- plugins/webida.editor.text-editor/TextEditorViewer.js (840)
- plugins/webida.editor.text-editor/Document.js (91)

In the view of plug-in developer, it's some verbose to see my own log and will it affect to performance?
Please remove log for it or change the level into debug/trace.

**Comment by hwshim** [comment]
@cimfalab : 
1) I see, I'll remove the log for entire file contents.
2) Also you can turn off the logger using ````logger.off();````
3) then you can make your own logger 
````
var logger = new Logger();
logger.off();
var myLogger = new Logger();
myLogger.info('some log');
````

**Comment by hwshim** [comment]
@cimfalab @wcho 

The heavy logs for the above files removed.
But for logs still remained, we will consider #232 multiple logger. in the next release (1.7.0).
So please wait until that.
Also we are planning to provide "log cleaner utility" for the building and deploying process.
Which will remove entire development stage log codes.
