### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by bd1978** [webida/webida-client#574]
Webida does not work on IE (version of supporting html5, over IE10).
It's very critical issue for supporting web standard.
Many people still use IE, especially B2B market.

**Comment by kyungmi** [comment]
@bd1978 We have a plan to support cross browsing.

**Comment by bd1978** [comment]
@kyungmi Please put on this issue to top priority. We must support IE until November.

**Comment by kyungmi** [comment]
@bd1978 We're discussing about this issue now. I'll let you know the result soon.

**Comment by kyungmi** [comment]
Related with #539

**Comment by bd1978** [comment]
@kyungmi Thanks a lot :)
