### ISSUE TITLE
Keyboard shortcut for MultiContentEditorPart

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#582]

**Comment by cimfalab** [comment]
@hwshim
Keyboard shortcut does not work in MultiContentEditorPart.
For example, I can execute Project Wizard by 'Alt+N'.
But if I open 'test.svgx' with Multi Content Editor Example editor and focus Code Editor in it, I can not execute wizard by 'Alt+N'.

Referer: @gseok

**Comment by hwshim** [comment]
@cimfalab 
I'll check this issue a bit later. because I have to do "MenuSystem for Part" first.
Thanks.

**Comment by hwshim** [comment]
@cimfalab 
I checked this, but it works for 'Multi Content Editor'.
I guess this issue has been solved with some other fix.
I'll close this, if you have any problem with this open again.
Thanks.
