### ISSUE TITLE
Editor tab visible when full-screen view

### ISSUE THREAD

**Issue by leechwin** [webida/webida-client#587]
Editor tab visible when full-screen view.

Open many editor. -> Double-click on the view.

![image](https://cloud.githubusercontent.com/assets/510924/10602345/b4e1bfb2-7752-11e5-8103-e3c0fd62a742.png)

![image](https://cloud.githubusercontent.com/assets/510924/10602348/b8a896a2-7752-11e5-96a6-d841883fb4ae.png)

**Comment by hwshim** [comment]
@leechwin 
What do you think desired result for this?
Without tab click (of full screen), how could we restore full screen back to normal?

**Comment by happibum** [comment]
Fixed by #613.
