### ISSUE TITLE
Feedback of tab moving disappeared (Result of applying the new webida theme)

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#590]
![image](https://cloud.githubusercontent.com/assets/7447396/10625789/90fbcc60-77e2-11e5-958f-ba6740f14bb8.png)
![image](https://cloud.githubusercontent.com/assets/7447396/10625790/a15e0d8e-77e2-11e5-81cd-760b0844ea2d.png)

**Comment by hwshim** [comment]
@woosys 
Please check the above issue.
Thanks.

**Comment by woosys** [comment]
Added missing style sheet. [PR#593](https://github.com/webida/webida-client/pull/593)

**Comment by hwshim** [comment]
@woosys 
Thanks!
