### ISSUE TITLE
"Save & Close" does not work in Multi Content Editor

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#605]
I opened test.svgx file with Multi Content Editor Example editor.
And I modified content in Code Editor (so dirty mark appears in tab)
and I closed the file.
So confirmation dialog pop-ups.
But although I selected "Save & Close",
- Dialog is not disappeared
- The opened file is not closed (dirty mark disappears)

Please check in a hurry ^^;
@gseok Please refer.

**Comment by cimfalab** [comment]
@hwshim : Please tell the progress of this issue.

**Comment by hwshim** [comment]
@cimfalab 

I'm planning to check this in this week.
Thanks.

**Comment by hwshim** [comment]
Solved #696
Thanks.

**Comment by hyunjongpark** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

phjwithyou@naver.com 님께 보내신 메일 <Re: [webida-client] "Save & Close" does not work in Multi Content Editor (#605)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by cimfalab** [comment]
@hwshim 
I checked it's working in .net site.
Thank you.
