### ISSUE TITLE
Handle JSON parse error of project.json in project configuratior

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#606]
When project.json is corrupted, an SyntaxError exception occurs in projectConfigurator.js:184.
After the exception throws, workspace context menu does not work and editor also doesn't work properly.

**Comment by kyungmi** [comment]
@wcho I'll check it. In what case application or person produces currupted project.json file?

**Comment by wcho** [comment]
An example is that the json file become empty when writing file failed by some reason. Empty file is an invalid json file.

**Comment by kyungmi** [comment]
IDE became loaded without error on IE10/11.

You can refer below PRs.
* webida-client: #750
* webida-dashboard: webida/webida-dashboard/pull/100

**Comment by hwshim** [comment]
@wcho 

Please check if there's no problem and close this issue.
Thanks.

**Comment by wcho** [comment]
It's fixed.
