### ISSUE TITLE
Shortcuts for Edit menu are not displayed in the menu bar

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#615]
Shortcuts for Edit menu are not displayed in the menu bar.
For example,
- 'Beautify All' (Shift+Alt+B) in the menu bar Edit > Source
- 'Indent' (Ctrl+]) in the menu bar Edit > Line

But if I hit the key, it works nicely.
Please check.

**Comment by hyukmin-kwon** [comment]
- It is the gap between workbench and editors shortcuts.
- We resolved similar issues by setting default shortcut.

**Comment by cimfalab** [comment]
Do you mean the issue I mentioned was resolved in the .net site?
I can't see the shortcut label in the menu bar.
I wonder #505 is resolving this. (or is it planned?)

**Comment by cimfalab** [comment]
This issue was resolved some ago.
