### ISSUE TITLE
Malfunction of reload.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#623]
**Test Case for Reload**
Environment:
* Two IDEs are opened with the same name of workspace.
(Let's call two IDEs like these : IDE1, IDE2)
* In the workspace, a project must exists with any files.

Step:
1. Open one of files in the IDE1.
2. Open the same file which was opened in the IDE2.
3. Edit and save code in the file of IDE2.  --> 'Reload File' dialog pops up. 
4. Select 'Yes'. ---> The file of IDE1 has been changed as like the file of IDE2.

**Issue 1.** Reload dialog does not pop up in firefox. (Step3)

**Issue 2.** In a git repository of IDE1,
After merged a file to git,  I tried to edit and save code. I expected a reload dialog to be popped up in IDE2. However, it doesn't. When the editor of a file gets a focus on it, the dialog pops up.

**Issue 3.** In the IDE1, 
1. Edit and save a README.md file.
2. Close the editor of README.md.
3. Git > Checkout from stage.
Reload dialog pops up even though it is already closed.
![image](https://cloud.githubusercontent.com/assets/7767406/10840712/5305a26a-7f25-11e5-93b3-3098744a1617.png)

**Comment by hwshim** [comment]
@JUHYUNCHOI 

Issue 1. Reload dialog does not pop up in firefox. (Step3) : Solved, test please

**Comment by hwshim** [comment]
![image](https://cloud.githubusercontent.com/assets/7447396/11301042/52faaea6-8fd7-11e5-844f-ae654bb26d25.png)

Issue 2 seems to be solved too, check them please

**Comment by JUHYUNCHOI** [comment]
I checked that all issues are solved.
