### ISSUE TITLE
Malfunction of context selection in the workspace.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#625]
** Test 1**
1. Expand git project.
2. Select the root of git project in the workspace.
3. Git > Show File History

** Issue 1. ** 
'Show File History' is enabled even though the root of git project is not a file.

** Issue 2. **
The result of step 3: The dialog of 'Show Repository History' is popped up not a 'Show File History'.

------------------------------------------------------------------------------------------------------------------------------

** Test 2**
1. Clone git repository. (It must be new. That is, it never been expanded in the workspace)

** Issue **
If git repository has not been expanded in the workspace, IDE does not recognize it as git repository.
Therefore,
No icon of git in the git project. No menu list for git project.

**Comment by JUHYUNCHOI** [comment]
I tried Test 2 again. 
Then, git repository is recognized as git project before expanding the project.
I think that the problem is occurred because of time. (It might be recognized late sometimes)
It is still a problem.

**Comment by minsung-jin** [comment]
done.(applied new menu framework)
