### ISSUE TITLE
Workspace View : Cannot read property 'isExpanded' of undefined

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#637]
![image](https://cloud.githubusercontent.com/assets/7447396/10901036/4173fa20-822b-11e5-8294-e675e626e673.png)

**Comment by hyukmin-kwon** [comment]
* This exeption occurs exactly after applying [commit 01c264b](https://github.com/webida/webida-client/commit/01c264b2e1a7199edef62e094418122173fc0b52).
 * @gotchazipc : please follow this issue.

**Comment by gotchazipc** [comment]
just simple, hot fix. plz review & merge.
