### ISSUE TITLE
Git Problem

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#650]
* Git clone is failed frequently.
* Git project remains previous status even though deleted the project.
    Step.
     1. Clone https://github.com/webida/webida-client.git
     2. Expand to common/src/webida/plugs/editors
     3. Edit DataSourceHandler.js > save.
     4. Delete git project(https://github.com/webida/webida-client.git)
     5. Re-clone https://github.com/webida/webida-client.git.
     6. Open DataSourceHandler.js.
   ==> Problems:
     . Some of paths to 'common/src/webida/plugs/editors' are expanded even though it is newly cloned.
       Therefore, it's too late to read information of files under the directory.
     . The data which is edited in the step 3 is remained in the step 6.
* Malfunction of reload after git reset --hard.
     Step.
      1. Edit, save and close any files in a git project.
      2. git reset --hard
      3. Open the file which is edited in the step1.
   ===> Problem:
      . The file is not reset.

**Comment by hwshim** [comment]
Solved with #662
