### ISSUE TITLE
i18n for workbench plugin

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#668]
webida-lib/plugins/editors
       webida-lib/plugins/workbench
       webida-lib/plugins/workspace
       plugins/webida.viewer.image-viewer
       plugins/webida.ide.notification.view
       plugins/webida.ide.notification.toast
       plugins/webida.editor.example.simple-editor
       plugins/webida.editor.example.svg
       plugins/webida.editor.example.multi-content

**Comment by minsung-jin** [comment]
related #575
