### ISSUE TITLE
Other user can open my workspace in the IDE

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#683]
This is a critical issue. The access control is not working.
I can open any user's workspace and edit the files.

**Comment by hwshim** [comment]
@gotchazipc 
@kyungmi 

Please check this right a way.
Is it real?

**Comment by darkain84** [comment]
Check the default id number 0 and PS.subject_id IN (IDs) of 'getPolicyBySubjectIdsAndResources'
Maybe number 0 of IN has the special meaning on the sql syntax.

**Comment by kyungmi** [comment]
@darkain84 I had found the same reason. I'll fix it. Thanks.

**Comment by kyungmi** [comment]
@wcho @darkain84 Number 0, 1 is a special id for subject. So It's only used for authorization. I just had looked up all usage of these special ids. Fortunately there are no more uses like this case.
I apologize for making this critical issue.

**Comment by kyungmi** [comment]
The bug has been fixed.
Refer to webida/webida-server#137
