### ISSUE TITLE
File download does not work when editor have a dirty file

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#705]
I have two files: index.html and resource.js
After I modify resource.js, (dirty mark appears)
I clicked 'Download' for index.html.
But the following dialog pop-ups.
* If "Leave", error page is shown saying {"result":"failed","reason":"Not authorized."}
* If "Don't Leave", nothing happens
![dirty1](https://cloud.githubusercontent.com/assets/762690/11266382/7f736d4c-8ee7-11e5-943f-8e57a51c2872.png)

Please check.
I think it may be related with beforeunload handler.

**Comment by hyukmin-kwon** [comment]
* The following case does not reappear and download works well.
 * If "Leave", error page is shown saying {"result":"failed","reason":"Not authorized."}

**Comment by cimfalab** [comment]
@hyukmin-kwon 
1. Ok. I also do not have "Leave" problem now. Is there any change related with it?
2. How do you think about "Don't Leave" case?

**Comment by hyukmin-kwon** [comment]
* The opening of the dialog is mysterious and I am analyzing that reason.

**Comment by hyukmin-kwon** [comment]
* Download is performed by using location.href. So 'onunload' event occurs. And 'onbeforeunload' event handler checks dirty. So the dialog appeared.
 * We solved this problem by using window.open() instead of changing locatio.href.
