### ISSUE TITLE
After merging #706 Editor's theme has gone away.

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#708]
After merging #706 Editor's theme has gone away.
Please check this.

* HEAD is now at b660e39 [BUGFIX] solve unexpected rendered tree hierarchies in preference dialog

![image](https://cloud.githubusercontent.com/assets/7447396/11271791/ce474654-8f0b-11e5-8e11-2de1f9f68715.png)

* HEAD is now at 3681995 [FEATURE] (#699) i18n for workspace plugin

![image](https://cloud.githubusercontent.com/assets/7447396/11271795/d2f3076a-8f0b-11e5-8b00-ace3e9bcbae3.png)

**Comment by kyungmi** [comment]
Sorry. Please check PR #711
