### ISSUE TITLE
[Bug] Context menu bug on dialog's text input with keyboard's popup key

### ISSUE THREAD

**Issue by bd1978** [webida/webida-client#716]
![cymera_20151120_182723](https://cloud.githubusercontent.com/assets/6582004/11296313/bf95bcfe-8fb4-11e5-9328-0b498f4c8fae.jpg)

![image-2015-11-20-030](https://cloud.githubusercontent.com/assets/6582004/11296208/2503938c-8fb4-11e5-8240-d7bf376ea1d7.png)

**Comment by gseok** [comment]
Current code is blocked all key event.
please change code.. block 'context' key event.
