### ISSUE TITLE
Cannot select name of directory to rename.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#763]
I selected a directory, named 'temp', and entered 'F2' to rename.

The directory name is not selected automatically.

![image](https://cloud.githubusercontent.com/assets/7767406/11434309/bbbb88c6-950d-11e5-8c89-c363dd444a1c.png)

When the name of a directory contains a '.' character,
the name is selected like below:
![image](https://cloud.githubusercontent.com/assets/7767406/11651765/81fa082a-9dd6-11e5-9a88-d62d0964fc6a.png)

**Comment by hyukmin-kwon** [comment]
* We applied a new selection policy which select entire name in the case of no '.'.
