### ISSUE TITLE
Find in Files (Patterns of excluded directory)

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#767]
Environment 
. A project exists.
. Two directories exist in the project. Let's call them directory1 and directory2.
. Both directories have a json file which 'name' is written in.

Step
1. Select project.
2. Find in files.
3. Input 'name' in the key word.
4. Input 'json' in the 'Searched file' in the Optional fields'
5. Input 'directory2' in the 'Excluded directories' in the 'Optional fields'.
6. Click find.

Result
Not found.

**Comment by minsung-jin** [comment]
It is in normal operation. Can't reproduce.

**Comment by JUHYUNCHOI** [comment]
For more information,
the problem was temporarily occurred because of a server problem.
