### ISSUE TITLE
Find in Files (Patterns of searched files)

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#768]
Environment 
. Project exists.
. Two directories exist in the project. Let's call them directory1 and directory2.
. The 'directory1' has a json file which 'name' is written in.
. The 'directory2' has a js file which 'name' is written in.

Step
1. Select project.
2. Find in files.
3. Input 'name' in the key word.
4. Input 'json' in the 'Searched file' in the Optional fields'
5. Click find.

Result
Not found.

**Comment by minsung-jin** [comment]
It is in normal operation. Can't reproduce.

**Comment by JUHYUNCHOI** [comment]
For more information,
the problem was temporarily occurred because of a server problem.
