### ISSUE TITLE
Jsdoc for sources in plugins.

### ISSUE THREAD

**Issue by hwshim** [webida/webida-client#773]
Please refer to http://usejsdoc.org/index.html
at least the following tags should be written.

@file : on top of the source code
@since : on top of the source code
@author : on top of the source code

@public
@private
@param
@returns
@abstract
@class
@method
@member
@override
@deprecated
@static

**Comment by minsung-jin** [comment]
- search plug-in
 - locale plug-in

**Comment by minsung-jin** [comment]
- workspace plugin completed.
