### ISSUE TITLE
'Cancel' operation works weird in Preferences

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#851]
In the Proferences,
I checked an option under Preview.
And I clicked 'Cancel'.

But if I open Preference dialog again,
the option I checked (but cancelled without applying) remains checked.
(Really, the option is not applied in run-time)

Please check.
It was originally reported by @yoonhyung.

**Comment by kyungmi** [comment]
@cimfalab @yoonhyung I'll check it.Thanks.
