### ISSUE TITLE
When Git Pull, Find in Files is run, IDE comes to unresponsiveness.(Chrome on Windows7 only)

### ISSUE THREAD

**Issue by yserlee** [webida/webida-client#854]
When I use Git Pull or Find in Files, IDE always comes to unresponsiveness.
So I can't use these features.
I used Chrome browser.
And this bug did not occur in Firefox.

**Comment by kyungmi** [comment]
Change the assignee becase @minsung-jin cannot reproduce this issues with his Chrome browser.

**Comment by kyungmi** [comment]
It was fixed In all cases with PR #869
