### ISSUE TITLE
Too many 404 errors for tern requests

### ISSUE THREAD

**Issue by hyukmin-kwon** [webida/webida-client#865]
![image](https://cloud.githubusercontent.com/assets/11404002/11973534/cdd27b64-a99e-11e5-8a92-e5aae8c8869b.png)

* Sometimes, tern requests files that may not exist. In this case, it is better to prevent 404 error messages.

**Comment by kyungmi** [comment]
@hyukmin-kwon @happibum I'll add an option (e.g. `mayNotExist`) to the readFile API. If this options is `true`, server will response with 204(No Conent) status code in error case of 404.

**Comment by kyungmi** [comment]
@hyukmin-kwon @happibum I've just modified as you want. Check this(https://github.com/webida/webida-client/commit/48f076ff0a1c11dc8ce2572c94926d56f83bec8b) please.
