### ISSUE TITLE
Run configurations' behavior is weird

### ISSUE THREAD

**Issue by cimfalab** [webida/webida-client#884]
I tried to log-in as a (new) guest.

1. Open Run Configuations dialog
 * "Run" and "Close" buttons are partially overlapped by main panel.
 * Plus(+) button has unintended active border.
 ![r1](https://cloud.githubusercontent.com/assets/762690/12500336/963b5ad6-c0f5-11e5-8ee4-141e7b346e5e.png)

2. Close dialog without applying it
 * "undefined" configuration is displayed in run configurations.
 ![r2](https://cloud.githubusercontent.com/assets/762690/12500337/966194d0-c0f5-11e5-81a3-239d7d2deffa.png)

3. Re-open Run Configuations dialog
 * Run Configurations UI is totally broken.
 ![r3](https://cloud.githubusercontent.com/assets/762690/12500338/969e80d4-c0f5-11e5-914e-29032f3d3669.png)

**Comment by hwshim** [comment]
@minsung-jin 
Please check this issue.
Thanks.

**Comment by cimfalab** [comment]
Hmm. Above 2 and 3 issues are resovled also? (or not reproduced?)

**Comment by minsung-jin** [comment]
It's being reproduced and tested.

**Comment by minsung-jin** [comment]
Not currently reproduce. When reproduce'll check again.
